# Generated by Django 4.1 on 2025-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activity",
            table="activity",
        ),
        migrations.AlterModelTable(
            name="leaderboard",
            table="leaderboard",
        ),
        migrations.AlterModelTable(
            name="team",
            table="teams",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="workout",
            table="workouts",
        ),
    ]
