# Generated by Django 4.1 on 2025-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "octofit_tracker",
            "0002_alter_activity_table_alter_leaderboard_table_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(to="octofit_tracker.user"),
        ),
    ]
